name: CI/CD Workflow

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Build and tag Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/chatapplicatie-backend:latest .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/chatapplicatie-backend:postgres-latest .

      - name: Push Docker images to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/chatapplicatie-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/chatapplicatie-backend:postgres-latest

  download-artifact:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker images artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-images
          path: ${{ github.workspace }}/downloaded-images

      - name: Verify downloaded Docker images
        run: ls -l ${{ github.workspace }}/downloaded-images

#test